In [32]:
pip install -e .

Obtaining file:///Users/user1/Documents/gsscoder_python/example_use
ERROR: file:///Users/user1/Documents/gsscoder_python/example_use does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import packages
import pandas as pd
from gsscoder_python import recode_gss
import zipfile

In [2]:
LOCAL_PARQUET_ZIP_PATH = "/Users/user1/Documents/domestic_rates_preprocessing/test_data/old_series_data/origin_destination_2002_to_2020.parquet.zip"
LOCAL_NEW_SERIES_PARQ = "/Users/user1/Documents/domestic_rates_preprocessing/test_data/combined/cleaned_data_combined.parquet"
LOCAL_OUTPUT_DIR = "/Users/user1/Documents/domestic_rates_preprocessing/test_data/new_geog_combined/output_parquet"

START_YR_NEW_SERIES = 2012
GSS_OLD_YEAR = 2021
GSS_NEW_YEAR = 2023

print("🚀 Starting local combine_series...")

# 1. Unzip and load the old series Parquet
print("📥 Reading ZIP from local file...")
with zipfile.ZipFile(LOCAL_PARQUET_ZIP_PATH, 'r') as zip_ref:
    parquet_name = zip_ref.namelist()[0]
    print(f"📦 Unzipping and reading {parquet_name}")
    with zip_ref.open(parquet_name) as f:
        df_old = pd.read_parquet(f)

df_old = df_old[df_old['year'] < START_YR_NEW_SERIES]
print(f"✅ Loaded old series shape: {df_old.shape}")

# 2. Recode gss_in
df_in_gss = df_old[df_old['gss_in'].str.contains("E0|W0")]
df_not_in_gss = df_old[~df_old['gss_in'].str.contains("E0|W0")]

print(f"🔄 Recoding gss_in from {GSS_OLD_YEAR} to {GSS_NEW_YEAR}...")
df_in_gss_recoded = recode_gss(
    df_in=df_in_gss,
    col_code='gss_in',
    col_data='value',
    fun='sum',
    recode_from_year=GSS_OLD_YEAR,
    recode_to_year=GSS_NEW_YEAR,
)

🚀 Starting local combine_series...
📥 Reading ZIP from local file...
📦 Unzipping and reading origin_destination_2002_to_2020.parquet
✅ Loaded old series shape: (19705748, 6)
🔄 Recoding gss_in from 2021 to 2023...

In [3]:
# Read the pickle file ad_code_changes.pickle
lad_code_changes = pd.read_pickle('/Users/user1/Documents/gsscoder_python/gsscoder_python/lookups/lad_code_changes.pickle')

In [36]:
lad_code_changes

,changed_to_code,changed_to_name,changed_from_code,changed_from_name,desc,entity_type,date,year,split,merge
242415,E06000049,Cheshire East,E07000017,Macclesfield,The Cheshire (Structural Changes) Order 2008,E06,2009-04-01,2009,False,True
242416,E06000050,Cheshire West and Chester,E07000013,Chester,The Cheshire (Structural Changes) Order 2008,E06,2009-04-01,2009,False,True
242417,E06000050,Cheshire West and Chester,E07000016,Ellesmere Port & Neston,The Cheshire (Structural Changes) Order 2008,E06,2009-04-01,2009,False,True
242418,E06000050,Cheshire West and Chester,E07000018,Vale Royal,The Cheshire (Structural Changes) Order 2008,E06,2009-04-01,2009,False,True
242419,E06000051,Shropshire,E07000182,Bridgnorth,The Shropshire (Structural Change) Order 2008,E06,2009-04-01,2009,False,True
...,...,...,...,...,...,...,...,...,...,...
499737,E06000065,North Yorkshire,E07000169,Selby,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499738,E06000066,Somerset,E07000187,Mendip,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499739,E06000066,Somerset,E07000188,Sedgemoor,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499740,E06000066,Somerset,E07000189,South Somerset,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499741,E06000066,Somerset,E07000246,Somerset West and Taunton,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True

In [37]:
# convert year to int
lad_code_changes['year'] = lad_code_changes['year'].astype(int)

In [38]:
#see all change 2021 to 2023
changes = lad_code_changes[
    (lad_code_changes['year'] >= 2020) & 
    (lad_code_changes['year'] <= 2023)
]

In [39]:
changes_2022 = lad_code_changes[lad_code_changes['year'] == 2022]

In [40]:
changes_2022

Empty DataFrame
Columns: [changed_to_code, changed_to_name, changed_from_code, changed_from_name, desc, entity_type, date, year, split, merge]
Index: []

In [17]:
changes

,changed_to_code,changed_to_name,changed_from_code,changed_from_name,desc,entity_type,date,year,split,merge
444851,E06000060,Buckinghamshire,E07000004,Aylesbury Vale,The Buckinghamshire (Structural Changes) Order...,E06,2020-04-01,2020,False,True
444852,E06000060,Buckinghamshire,E07000005,Chiltern,The Buckinghamshire (Structural Changes) Order...,E06,2020-04-01,2020,False,True
444853,E06000060,Buckinghamshire,E07000006,South Bucks,The Buckinghamshire (Structural Changes) Order...,E06,2020-04-01,2020,False,True
444854,E06000060,Buckinghamshire,E07000007,Wycombe,The Buckinghamshire (Structural Changes) Order...,E06,2020-04-01,2020,False,True
445542,E06000061,North Northamptonshire,E07000150,Corby,The Northamptonshire (Structural Changes) Orde...,E06,2021-04-01,2021,False,True
445543,E06000061,North Northamptonshire,E07000152,East Northamptonshire,The Northamptonshire (Structural Changes) Orde...,E06,2021-04-01,2021,False,True
445544,E06000061,North Northamptonshire,E07000153,Kettering,The Northamptonshire (Structural Changes) Orde...,E06,2021-04-01,2021,False,True
445545,E06000061,North Northamptonshire,E07000156,Wellingborough,The Northamptonshire (Structural Changes) Orde...,E06,2021-04-01,2021,False,True
445546,E06000062,West Northamptonshire,E07000151,Daventry,The Northamptonshire (Structural Changes) Orde...,E06,2021-04-01,2021,False,True
445547,E06000062,West Northamptonshire,E07000154,Northampton,The Northamptonshire (Structural Changes) Orde...,E06,2021-04-01,2021,False,True
445548,E06000062,West Northamptonshire,E07000155,South Northamptonshire,The Northamptonshire (Structural Changes) Orde...,E06,2021-04-01,2021,False,True
499725,E06000063,Cumberland,E07000026,Allerdale,The Cumbria (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499726,E06000063,Cumberland,E07000028,Carlisle,The Cumbria (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499727,E06000063,Cumberland,E07000029,Copeland,The Cumbria (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499728,E06000064,Westmorland and Furness,E07000027,Barrow-in-Furness,The Cumbria (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499729,E06000064,Westmorland and Furness,E07000030,Eden,The Cumbria (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499730,E06000064,Westmorland and Furness,E07000031,South Lakeland,The Cumbria (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499731,E06000065,North Yorkshire,E07000163,Craven,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499732,E06000065,North Yorkshire,E07000164,Hambleton,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499733,E06000065,North Yorkshire,E07000165,Harrogate,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499734,E06000065,North Yorkshire,E07000166,Richmondshire,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499735,E06000065,North Yorkshire,E07000167,Ryedale,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499736,E06000065,North Yorkshire,E07000168,Scarborough,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499737,E06000065,North Yorkshire,E07000169,Selby,The North Yorkshire (Structural Changes) Order...,E06,2023-04-01,2023,False,True
499738,E06000066,Somerset,E07000187,Mendip,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499739,E06000066,Somerset,E07000188,Sedgemoor,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499740,E06000066,Somerset,E07000189,South Somerset,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True
499741,E06000066,Somerset,E07000246,Somerset West and Taunton,The Somerset (Structural Changes) Order 2022,E06,2023-04-01,2023,False,True

In [ ]:
df_in_gss_recoded 
#change the gss_in column name to 'gss_in_recoded'
df_in_gss_recoded.rename(columns={'gss_in': 'gss_in_recoded'}, inplace=True)

In [9]:
df_in_gss

            gss_out     gss_in    year     sex   age   value
0         E06000001  E06000002  2002.0  female   7.0  1.1805
1         E06000001  E06000002  2002.0  female   8.0  1.1805
2         E06000001  E06000002  2002.0  female   9.0  1.1805
3         E06000001  E06000002  2002.0  female  11.0  2.3610
4         E06000001  E06000002  2002.0  female  12.0  1.1805
...             ...        ...     ...     ...   ...     ...
29937902  W06000024  W06000023  2011.0    male  34.0  1.1264
29937903  W06000024  W06000023  2011.0    male  38.0  1.1264
29937904  W06000024  W06000023  2011.0    male  43.0  1.1264
29937905  W06000024  W06000023  2011.0    male  52.0  1.1264
29937906  W06000024  W06000023  2011.0    male  57.0  1.1264

[19438723 rows x 6 columns]

In [11]:
df_in_gss_recoded

            gss_out gss_in_recoded    year     sex   age   value
0         E06000001      E06000002  2002.0  female   7.0  1.1805
1         E06000001      E06000002  2002.0  female   8.0  1.1805
2         E06000001      E06000002  2002.0  female   9.0  1.1805
3         E06000001      E06000002  2002.0  female  11.0  2.3610
4         E06000001      E06000002  2002.0  female  12.0  1.1805
...             ...            ...     ...     ...   ...     ...
19438718  W06000024      W06000023  2011.0    male  34.0  1.1264
19438719  W06000024      W06000023  2011.0    male  38.0  1.1264
19438720  W06000024      W06000023  2011.0    male  43.0  1.1264
19438721  W06000024      W06000023  2011.0    male  52.0  1.1264
19438722  W06000024      W06000023  2011.0    male  57.0  1.1264

[19438723 rows x 6 columns]

In [30]:
#search gss_in E07000155
df_in_gss[df_in_gss['gss_in'].str.contains("E07000026")]

            gss_out     gss_in    year     sex   age   value
13359     E06000001  E07000026  2002.0  female   0.0  0.0666
13360     E06000001  E07000026  2002.0  female  13.0  1.0894
13361     E06000001  E07000026  2002.0  female  19.0  0.1212
13362     E06000001  E07000026  2002.0  female  32.0  1.0894
13363     E06000001  E07000026  2002.0    male   0.0  0.0891
...             ...        ...     ...     ...   ...     ...
29866539  W06000023  E07000026  2010.0  female   0.0  0.1070
29866540  W06000023  E07000026  2011.0  female  29.0  1.2273
29866541  W06000023  E07000026  2011.0    male   0.0  0.1139
29916840  W06000024  E07000026  2004.0  female  35.0  1.0588
29916841  W06000024  E07000026  2009.0    male  19.0  1.3214

[32004 rows x 6 columns]

In [31]:
#search gss_in E07000155
df_in_gss_recoded[df_in_gss_recoded['gss_in_recoded'].str.contains("E07000026")]

            gss_out gss_in_recoded    year     sex   age   value
8611      E06000001      E07000026  2002.0  female   0.0  0.0666
8612      E06000001      E07000026  2002.0  female  13.0  1.0894
8613      E06000001      E07000026  2002.0  female  19.0  0.1212
8614      E06000001      E07000026  2002.0  female  32.0  1.0894
8615      E06000001      E07000026  2002.0    male   0.0  0.0891
...             ...            ...     ...     ...   ...     ...
19392440  W06000023      E07000026  2010.0  female   0.0  0.1070
19392441  W06000023      E07000026  2011.0  female  29.0  1.2273
19392442  W06000023      E07000026  2011.0    male   0.0  0.1139
19423998  W06000024      E07000026  2004.0  female  35.0  1.0588
19423999  W06000024      E07000026  2009.0    male  19.0  1.3214

[32004 rows x 6 columns]